name: TARINI BHATNAGAR
url: https://tarinib.github.io/
description: Aspiring Geo + Data Scientist

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
